version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: employee_management_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee_management_web
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    command: ["uvicorn", "src.employee_management.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  mongo_data:
