[tool.poetry]
name = "employee-management"
version = "0.1.0"
description = "Application for manage employee in company"
authors = ["dewly-phuong <phuong.truong@dewly.ai>"]
readme = "README.md"
packages = [
  { include = "employee_management", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.13,<3.14"
fastapi = ">=0.136.1,<0.137.0"
uvicorn = ">=0.46.0,<0.47.0"
pydantic = {extras = ["email"], version = "^2.13.4"}
pymongo = ">=4.17.0,<5.0.0"
motor = ">=3.7.1,<4.0.0"
dotenv = ">=0.9.9,<0.10.0"
passlib = ">=1.7.4,<2.0.0"
python-jose = ">=3.5.0,<4.0.0"
beanie = "^2.1.0"
python-multipart = "^0.0.28"
pyjwt = "^2.12.1"
pwdlib = {extras = ["argon2"], version = "^0.3.0"}

[tool.poetry.group.dev.dependencies]
ruff = ">=0.15.12,<0.16.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
